name: Create and publish a Docker image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    #branches: ['main'] # Need to add an account to run with TODO

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Inject secrets - DISCORD_TOKEN
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "DISCORD_TOKEN"
          replace: "${{ secrets.DISCORD_TOKEN }}"
      - name: Inject secrets - REDDIT_CLIENT_ID
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "REDDIT_ID"
          replace: "${{ secrets.REDDIT_CLIENT_ID }}"
      - name: Inject secrets - REDDIT_CLIENT_SECRET
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "REDDIT_SECRET"
          replace: "${{ secrets.REDDIT_CLIENT_SECRET }}"
      - name: Inject secrets - REDDIT_PW
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "REDDIT_PASSWD"
          replace: "${{ secrets.REDDIT_PW }}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: actions/checkout@master
      - name: Send Discord message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: "Orgasmobot"
          message: "New Orgasmotron container has been built by yours truly"